---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ssh

  tasks:
   - name: make a directory
     file:
       path: ~/output/
       state: directory
   - name: use shell module with wildcarding
     shell: echo $HOME >> ~/output/path.txt
      # NOT idempotent (will run every time)
  #- name: use shell module with wildcarding
  #  shell: echo $HOME >> ~/output/path.txt

  # idempotent solution
   - name: use copy to avoid using a shell command
     copy:
       content: "{{ ansible_env.HOME }}"           # this retrieves env info from gathered facts ("left side" of the shell command)
       dest: ~/output/path.txt                     # ("right side" of the shell command)
       force: yes  
